CREATE DATABASE CASESTUDY_RETAIL

alter table transactions
alter column PROD_CAT_CODE int not null

select*from transactions


--DATA PREPARATION AND UNDERSTANDING
--1. What is the total number of rows in each of the 3 tables in the database?

select 'Customer'as tbl_name,count(*) as count_records from Customer 
union all
select 'Transactions', count(*) from Transactions 
union all
select 'Prod_cat_info', count(*)  from prod_cat_info 

--2. What is the total number of transactions that have a return?

select count(qty) as return_transactions from transactions
where qty<0

--3. As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead.
	  select tran_date, CONVERT(varchar(10), tran_date , 103) as converteddate  from Transactions 
      select DOB, CONVERT(varchar(10), DOB , 103) as converteddate  from Customer

--4. What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.--
    
Select MAX(tran_date) as Max_date,MIN(tran_date) AS min_date,
Datepart(Year,Max(tran_date))-datepart(Year,Min(tran_date)) AS years,Datepart(Month,Max(tran_date))-Datepart(Month,Min(tran_date)) AS Total_Months,
Datepart(Day,max(tran_date))-Datepart(Day,min(tran_date)) AS Total_Days
FROM Transactions


--5. Which product category does the sub-category “DIY” belong to?
     SELECT PROD_CAT,PROD_SUBCAT FROM PROD_CAT_INFO
	 WHERE PROD_SUBCAT='DIY'


--Data Analysis
--1. Which channel is most frequently used for transactions?
SELECT 
TOP 1
store_type,
count(store_type) as Count_channel
from transactions
group by Store_type
order by count(Store_type)desc


--Q.2 What is the count of Male and Female customers in the database?
SELECT
GENDER,
COUNT(GENDER) AS COUNT_MALE_FEMALE
FROM CUSTOMER
GROUP BY Gender
HAVING GENDER='M' OR GENDER='F'


--Q.3 From which city do we have the maximum number of customers and how many?
SELECT 
TOP 1
MAX(city_code) AS MAX_CITYCODE,
COUNT(CITY_CODE)AS COUNT_CITYCODE
FROM CUSTOMER 
GROUP BY city_code 
ORDER BY COUNT(city_code) DESC


--Q.4 How many sub-categories are there under the Books category?

Select 
PROD_CAT AS CATEGORY,
Count(prod_subcat) AS SUB_CATEGORY
From Prod_Cat_Info
Where prod_cat='Books'
GROUP BY prod_cat


--5.What is the maximum quantity of products ever ordered?

Select 
Top 1 pc.prod_cat,T.prod_cat_code,Sum(T.Qty) AS Max_Qty_Ordered from Transactions T join Prod_cat_info pc on Pc.prod_cat_code=T.Prod_cat_code and Pc.Prod_sub_cat_code=T.prod_subcat_code
Group by  T.prod_cat_code,Pc.prod_cat 
Order by sum(t.Qty) desc


--6. What is the net total revenue generated in categories Electronics and Books?
SELECT T.prod_cat_code,P.prod_cat ,SUM(CAST(total_amt as float)) AS NET_REVENUE_GENERATED
FROM Transactions AS T LEFT JOIN prod_cat_info AS P ON T.prod_cat_code=P.prod_cat_code AND T.prod_subcat_code=P.prod_sub_cat_code
WHERE prod_cat IN ('Books','Electronics')  
GROUP BY T.prod_cat_code,P.prod_cat

--7 How many customers have >10 transactions with us, excluding returns?
SELECT COUNT(*)AS COUNT_OF_CUSTOMERS FROM (SELECT 
CUST_ID,
COUNT(CUST_ID) AS CUSTOMER
FROM transactions
WHERE QTY>0
GROUP BY CUST_ID
HAVING COUNT(CUST_ID)>10)AS T1

--8. What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
SELECT
SUM(CAST(TOTAL_AMT as float)) AS TOTAL_REVENUE
From Transactions
WHERE prod_cat_code In (1,3)AND STORE_TYPE='FLAGSHIP STORE'

 
--9.What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.
SELECT
SUM(T.TOTAL_AMT),
PC.PROD_SUBCAT
FROM CUSTOMER C INNER JOIN TRANSACTIONS T ON C.customer_Id=T.cust_id
INNER JOIN prod_cat_info PC ON PC.prod_sub_cat_code=T.prod_subcat_code and pc.prod_cat_code = t.prod_cat_code
WHERE GENDER='M' AND PC.prod_cat='ELECTRONICS'
GROUP BY prod_subcat
ORDER BY prod_subcat



--10.	What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
--Percentage of sales
SELECT TOP 5 prod_subcat_code,100*SUM(CAST(total_amt as float))/(SELECT SUM(CAST(total_amt as float)) FROM Transactions WHERE Qty>0)
AS Percentage_of_sales
FROM Transactions
WHERE Qty>0
GROUP BY prod_subcat_code
ORDER BY Percentage_of_sales DESC

--Percentage of return
SELECT prod_subcat_code,100*SUM(CAST(total_amt as float))/(SELECT SUM(CAST(total_amt as float)) FROM Transactions WHERE Qty<0)
AS Percentage_of_return
FROM Transactions
WHERE Qty<0
GROUP BY prod_subcat_code
ORDER BY Percentage_of_return DESC


--11.For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?

Select t.cust_id, T.TRAN_DATE, sum(t.total_amt) from 
(SELECT *, MAX(T.tran_date) OVER() AS MAX_DATE FROM transactions T)T
INNER join Customer c on T.cust_id = c.customer_Id 
WHERE T.tran_date > DATEADD(DAY,-30,MAX_DATE) AND tran_date >= DATEADD(year,25,c.DOB) and T.tran_date <= DATEADD(year,35,c.DOB)
GROUP BY T.cust_id,tran_date


--12.	Which product category has seen the max value of returns in the last 3 months of transactions?


SELECT TOP 1 prod_cat_code,SUM(CAST(total_amt as float)) AS [RETURNS]
FROM Transactions
WHERE Qty<0 AND tran_date >  (SELECT DATEADD(MONTH,-3,MAX(tran_date)) FROM Transactions)
GROUP BY prod_cat_code
ORDER BY SUM(CAST(total_amt as float))


--13  Which store-type sells the maximum products; by value of sales amount and by quantity sold?

Select top 1 store_type,sum(Qty) as total_sales,sum(cast(total_amt as float)) as total_amount from transactions
Group by Store_type
Order by sum(Qty)desc

--14.	What are the categories for which average revenue is above the overall average.

Select Pc.Prod_cat,Avg(total_amt) As Avg_revenue From
(Select*,Avg(total_amt)over() As overall_avg from Transactions t)As T
inner join Prod_cat_info pc on Pc.prod_cat_code=T.Prod_cat_code and Pc.Prod_sub_cat_code=T.Prod_subcat_code
Group by Pc.Prod_cat,Overall_avg
Having Avg(Total_amt)>Overall_avg

--15 Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

Select Pc.prod_cat , Pc.prod_subcat  , Sum(cast(T.Total_amt as int)) as Sum_of_total_amt , Avg(Cast(T.Total_amt as int)) as Avg_of_total_amt From 
Prod_cat_info pc join Transactions T on pc.prod_cat_code = T.Prod_cat_code  and Pc.prod_sub_cat_code = T.prod_subcat_code
Where t.prod_cat_code in ( Select top 5 t.prod_cat_code  From transactions t 
Group by T.prod_cat_code order by sum(Cast(T.Qty as int)) desc)
Group by Pc.prod_cat , Pc.Prod_subcat 


